[project]
name = "jupyter-python-local-venv"
version = "0.0.1"
requires-python = ">= 3.5"
dependencies = [
    "pandas==2.2.2"
    ,"plotly==5.22.0"
    ,"ipykernel==6.29.5"
    ,"notebook==7.2.2"
    ,"matplotlib==3.9.2"
    ,"gravis==0.1.0"
    ,"networkx==3.2.1"
]